### ISSUE TITLE
Problem with Exchange Fallback

### ISSUE THREAD

**Issue by sudden-break** [florianv/laravel-swap#42]
Sometimes when I try to convert Bitcoin Cash to USD via Cryptonator/Open Exchangerates I receive the following exception:

```
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "USD/BCH" is not supported by the service "Exchanger\Service\OpenExchangeRates".
Exchanger\Exception\Exception: Service temporarily unavailable
```
That's my call:
`return $this->amount/Swap::latest('USD/BCH')->getValue()*1;`

And I have Open Exchangerates before Cryptonator in my config.
Seems like as Open Exchangerates doesn't have Bitcoin Cash rates, it raises an error and doesn't fallback to cryptonator.

**Comment by florianv** [comment]
Thanks for reporting this @sudden-break! 

The issue is that in `florianv/exchanger`, we are not catching http request exceptions right now, so it passes through the chain provider and emits the exception.

It was done so if you misconfigure a service, for example with an invalid key, you have immediate feedback with the Exception thrown, instead of having the whole chain to run.

But in your case, I agree that it should fallback to the `cryptonator` provider. Maybe we should catch all http exceptions and let the chain run.

**Comment by florianv** [comment]
@sudden-break To me it looks like that open exchange rates doesn't have the pair and cryptonator returns an error so it looks correct ?
