### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by Amodar** [florianv/laravel-swap#70]

**Comment by Amodar** [comment]
For the people who can't wait to move to Laravel 6, I've created a temporary fork that supports it. https://github.com/Amodar/laravel-swap. Please note the fork will be archived once this repo supports it.

**Comment by geodro** [comment]
Any plans to add support soon?

**Comment by florianv** [comment]
@Amodar Can you please send a pull request ? Thanks!

**Comment by niladam** [comment]
Hi @florianv,

First of all i want to **thank you** for your hard work!:)

Second,  from what i can gather, the issue lies in the upstream [php-cache/illuminate-adapter](https://github.com/php-cache/illuminate-adapter) which didn't [add support](https://github.com/php-cache/illuminate-adapter/blob/master/composer.json#L38) for illuminate/cache 6.0;

In order for him to be able to send a PR, i think this will require @Amodar to also send a PR to @php-cache/illuminate-adapter -- which sadly is readonly..so that's a bummer.

What @Amodar did was also fork [@php-cache/illuminate-adapter](https://github.com/php-cache/illuminate-adapter/compare/master...Amodar:master) and added support for [illuminate/cache 6.0](https://github.com/illuminate/cache).

I'm looking forward to this support anyhow, as i'm building something that might put your package do some heavy lifting!

**Comment by leeovery** [comment]
Turns out at some point (maybe Laravel 6) the cache repository interface was updated to fully adhere to the SimpleCache contract.

So you can now just pass the Laravel cache repository into the Swap Builder `useSimpleCache` method:

```php
$builder = (new Builder)->useSimpleCache(resolve(\Illuminate\Contracts\Cache\Repository::class));
```

The config can then be updated to remove the cache part as this will automatically use what's set in the Laravel cache.php config / env.

**Comment by Amodar** [comment]
@florianv here it is https://github.com/florianv/laravel-swap/pull/72. I'm not a fan of this change though as we're dependent on illuminate-adapter which is not maintained anymore.

**Comment by kslimani** [comment]
Any progress on Laravel 6 support ?

EDIT: i pushed a possible alternative proposition (#73) to fix this issue.

**Comment by mits87** [comment]
Any progress about Laravel 6 support?

**Comment by kslimani** [comment]
@mits87 Laravel 6 is supported since release [2.1.0](https://github.com/florianv/laravel-swap/releases/tag/2.1.0).

@florianv : I think this issue should be closed ?

**Comment by florianv** [comment]
@kslimani Yes!
